package ru.vdv.myexchangerates.domain

import com.google.gson.annotations.SerializedName

data class Valute(
    @SerializedName("AUD") var AUD: Currency? = Currency(),
    @SerializedName("AZN") var AZN: Currency? = Currency(),
    @SerializedName("GBP") var GBP: Currency? = Currency(),
    @SerializedName("AMD") var AMD: Currency? = Currency(),
    @SerializedName("BYN") var BYN: Currency? = Currency(),
    @SerializedName("BGN") var BGN: Currency? = Currency(),
    @SerializedName("BRL") var BRL: Currency? = Currency(),
    @SerializedName("HUF") var HUF: Currency? = Currency(),
    @SerializedName("HKD") var HKD: Currency? = Currency(),
    @SerializedName("DKK") var DKK: Currency? = Currency(),
    @SerializedName("USD") var USD: Currency? = Currency(),
    @SerializedName("EUR") var EUR: Currency? = Currency(),
    @SerializedName("INR") var INR: Currency? = Currency(),
    @SerializedName("KZT") var KZT: Currency? = Currency(),
    @SerializedName("CAD") var CAD: Currency? = Currency(),
    @SerializedName("KGS") var KGS: Currency? = Currency(),
    @SerializedName("CNY") var CNY: Currency? = Currency(),
    @SerializedName("MDL") var MDL: Currency? = Currency(),
    @SerializedName("NOK") var NOK: Currency? = Currency(),
    @SerializedName("PLN") var PLN: Currency? = Currency(),
    @SerializedName("RON") var RON: Currency? = Currency(),
    @SerializedName("XDR") var XDR: Currency? = Currency(),
    @SerializedName("SGD") var SGD: Currency? = Currency(),
    @SerializedName("TJS") var TJS: Currency? = Currency(),
    @SerializedName("TRY") var TRY: Currency? = Currency(),
    @SerializedName("TMT") var TMT: Currency? = Currency(),
    @SerializedName("UZS") var UZS: Currency? = Currency(),
    @SerializedName("UAH") var UAH: Currency? = Currency(),
    @SerializedName("CZK") var CZK: Currency? = Currency(),
    @SerializedName("SEK") var SEK: Currency? = Currency(),
    @SerializedName("CHF") var CHF: Currency? = Currency(),
    @SerializedName("ZAR") var ZAR: Currency? = Currency(),
    @SerializedName("KRW") var KRW: Currency? = Currency(),
    @SerializedName("JPY") var JPY: Currency? = Currency()
)
